[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "qiboml"
version = "0.0.1"
description = "Quantum Machine Learning using Qibo"
authors = ["Matteo Robbiati <matteo.robbiati@cern.ch>"]
readme = "README.md"
packages = [{ include = "qiboml", from = "src" }]

[tool.poetry.dependencies]
python = ">=3.9,<3.12"
numpy = "^1.26.4"
numba = "^0.59.0"
tensorflow = "^2.16.1"
qibo = "^0.2.6"

[tool.poetry.group.dev.dependencies]
ipython = "^7.34"
pdbpp = "^0.10.3"

[tool.poetry.group.benchmark.dependencies]
pytest = "^8.0.0"
pylint = "^2.17"
pytest-benchmark = { version = "^4.0.0", extras = ["histogram"] }

[tool.poe.tasks]
bench = "pytest benchmarks/"
test = "pytest"
lint = "pylint src/**/*.py -E"
lint-warnings = "pylint src/**/*.py --exit-zero"

[tool.pytest.ini_options]
testpaths = ['tests/', 'benchmarks/']
python_files = ['test_*.py', 'bench_*.py']
python_classes = ['Test*', 'Benchmark*']
python_functions = ['test_*', 'bench_*']
addopts = [
  "--benchmark-warmup=on",
  "--benchmark-warmup-iterations=100000",
  "--benchmark-disable-gc",
  "--benchmark-histogram=bench-hists/bench",
]
