name: docs

on:
  workflow_dispatch:
  push:

jobs:
  evaluate-label:
    runs-on: ubuntu-latest
    outputs:
      label: ${{ steps.label_step.outputs.version }}
    steps:
      - name: Check label for deployment
        id: label_step
        run: echo "version=stable" >> $GITHUB_OUTPUT
          

  deploy-docs:
    needs: [evaluate-label]
    uses: qiboteam/workflows/.github/workflows/deploy-ghpages-latest-stable.yml@v1
    with:
      python-version: "3.12"
      package-manager: "poetry"
      dependency-path: "**/poetry.lock"
      trigger-label: "${{ needs.evaluate-label.outputs.label }}"
      poetry-extras: --with docs
      project: qiboml
